# Docker Compose pour MongoDB - AI Chatbot Backend
# 
# Ce fichier configure :
# - MongoDB avec authentification
# - Mongo Express (interface web optionnelle)
# - Volumes persistants pour les données
# - Réseau isolé


services:
  # === SERVICE MONGODB ===
  mongodb:
    image: mongo:7.0
    container_name: ai-chatbot-mongodb
    restart: unless-stopped
    
    # Variables d'environnement pour MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: chatbot2025
      MONGO_INITDB_DATABASE: ai-chatbot
    
    # Ports exposés (27017 = port MongoDB standard)
    ports:
      - "27017:27017"
    
    # Volume persistant pour les données
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    
    # Réseau personnalisé
    networks:
      - chatbot-network
    
    # Configuration de santé
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # === SERVICE MONGO EXPRESS (Interface Web) ===
  # Optionnel - Interface graphique pour gérer MongoDB
  mongo-express:
    image: mongo-express:1.0.2
    container_name: ai-chatbot-mongo-express
    restart: unless-stopped
    
    # Dépend de MongoDB
    depends_on:
      mongodb:
        condition: service_healthy
    
    # Variables d'environnement pour Mongo Express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: chatbot2025
      ME_CONFIG_MONGODB_URL: mongodb://admin:chatbot2025@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    
    # Port pour l'interface web
    ports:
      - "8082:8082"
    
    # Réseau personnalisé
    networks:
      - chatbot-network

# === VOLUMES PERSISTANTS ===
volumes:
  mongodb_data:
    driver: local
    name: ai-chatbot-mongodb-data
  mongodb_config:
    driver: local
    name: ai-chatbot-mongodb-config

# === RÉSEAU PERSONNALISÉ ===
networks:
  chatbot-network:
    driver: bridge
    name: ai-chatbot-network
